const KEY='hyrox75-v1';
const plans={0:['Sunday · Recovery','Recover and prepare for the next week.','Recovery',[['Easy walk','45–60 min'],['Mobility','10 min']]],1:['Monday · Push + Abs','Upper-body strength; leave 2–3 reps in reserve.','Strength',[['DB Flat Bench Press','3 × 8–12'],['DB Incline Bench Press','3 × 8–12'],['Shoulder Press','2 × 8–12'],['Lateral Raise','3 × 12–15'],['Triceps Extension','2 × 10–15'],['Triceps Pushdown','2 × 10–15'],['Crunch','2 × 15'],['Leg Raise','2 × 10–15']]],2:['Tuesday · Aerobic Engine','Build endurance without excessive leg damage.','Engine',[['Zone 2','35–40 min'],['SkiErg','3 × 500 m'],['Farmer Carry','3 × 30 m'],['Pallof Press','3 × 10/side'],['Dead Bug','3 × 10']]],3:['Wednesday · Pull + Core','Back, biceps and posture.','Strength',[['Lat Pulldown','3 × 8–12'],['Seated Row','3 × 8–12'],['DB Shrug','2 × 12'],['Back Extension','2 × 10–12'],['DB Curl','3 × 10–12'],['Hammer Curl','3 × 10–12'],['Face Pull','2 × 15']]],4:['Thursday · HYROX Intervals','Hard but controlled race-specific conditioning.','HYROX',[['Run','4 × 750 m'],['SkiErg','4 × 250 m'],['Burpees','4 × 10']]],5:['Friday · Legs','Strength without destroying Saturday. No failure or drop sets.','Strength',[['Squat','3 × 6–8 · RPE 7'],['Romanian Deadlift','2 × 8–10 · RPE 7'],['Bulgarian Split Squat','2 × 8/leg'],['Leg Curl','2 × 10–12'],['Calf Raise','2 × 12–15']]],6:['Saturday · HYROX Simulation','Race-specific endurance. Week 1 starts with 3 rounds.','HYROX',[['Run','3 × 1 km'],['Row','3 × 500 m'],['Walking Lunges','3 × 20'],['Wall Balls','3 × 20']]]};
const roadmap=['Foundation','Foundation','Build','Build','Simulate','Simulate','Race Prep','Full HYROX'];
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{weight:88,rounds:0,history:[],notes:'',custom:[]};
const $=id=>document.getElementById(id);const day=new Date().getDay();const plan=plans[day];
$('todayTitle').textContent=plan[0];$('todayDesc').textContent=plan[1];$('todayTag').textContent=plan[2];$('weight').value=state.weight;$('rounds').value=state.rounds;
function renderStats(){const lost=Math.max(0,88-Number($('weight').value||88));$('stats').innerHTML=`<div class="stat"><span>Current</span><strong>${Number($('weight').value||88).toFixed(1)} kg</strong></div><div class="stat"><span>Goal</span><strong>75.0 kg</strong></div><div class="stat"><span>Lost</span><strong>${lost.toFixed(1)} kg</strong></div><div class="stat"><span>HYROX</span><strong>${Math.min(8,Number($('rounds').value||0))}/8</strong></div><div class="stat"><span>Phase</span><strong>Week 1</strong></div>`;$('remaining').textContent=`${Math.max(0,Number($('weight').value||88)-75).toFixed(1)} kg remaining`;$('weightTrack').style.width=`${Math.min(100,Math.max(0,(88-Number($('weight').value||88))/13*100))}%`}
function makeExercise(name,target,custom=false){const el=document.createElement('div');el.className='exercise';el.innerHTML=`<div class="exercise-top"><input type="checkbox" class="done" aria-label="Complete ${name}"><span class="exercise-name">${name}</span><button class="remove" type="button">${custom?'Remove':'Remove'}</button></div><div class="target">Target: ${target}</div><div class="exercise-fields"><label>Actual<input class="actual" placeholder="reps / distance / time"></label><label>Load / pace<input class="load" placeholder="kg / pace"></label><label>Notes<input class="rownotes" placeholder="optional"></label></div>`;el.querySelector('.done').addEventListener('change',()=>{el.classList.toggle('done',el.querySelector('.done').checked);progress()});el.querySelector('.remove').addEventListener('click',()=>{el.remove();progress()});$('exerciseList').appendChild(el)}
plan[3].forEach(x=>makeExercise(x[0],x[1]));(state.custom||[]).filter(x=>x.day===day).forEach(x=>makeExercise(x.name,x.target,true));
function progress(){const all=[...document.querySelectorAll('.exercise')],done=all.filter(x=>x.querySelector('.done').checked).length,p=all.length?Math.round(done/all.length*100):0;$('sessionProgress').style.width=p+'%';$('sessionProgressText').textContent=`${p}% complete · ${done}/${all.length} activities`}
$('addExercise').addEventListener('click',()=>{const name=prompt('Exercise or activity name');if(!name)return;const target=prompt('Target (e.g. 3 × 10, 20 min)')||'Custom';makeExercise(name,target,true);state.custom=state.custom||[];state.custom.push({day,name,target});localStorage.setItem(KEY,JSON.stringify(state));progress()});
$('weight').addEventListener('input',renderStats);$('rounds').addEventListener('input',renderStats);
function save(){state.weight=Number($('weight').value||88);state.rounds=Math.min(8,Math.max(0,Number($('rounds').value||0)));state.notes=$('notes').value;const rows=[...document.querySelectorAll('.exercise')];const done=rows.filter(x=>x.querySelector('.done').checked);const details=done.map(x=>`${x.querySelector('.exercise-name').textContent} — ${x.querySelector('.actual').value||'completed'}${x.querySelector('.load').value?' @ '+x.querySelector('.load').value:''}`).join('\n');const entry={date:new Date().toLocaleDateString(),weight:state.weight,rounds:state.rounds,done:done.length,total:rows.length,details,notes:state.notes};state.history.unshift(entry);state.history=state.history.slice(0,30);localStorage.setItem(KEY,JSON.stringify(state));renderStats();renderHistory();$('emailBody').value=`Subject: HYROX 75 — ${plan[0]} achievement\n\nToday I completed ${done.length}/${rows.length} planned activities.\n\nWeight: ${state.weight.toFixed(1)} kg\nHYROX rounds: ${state.rounds}/8\n\n${details||'No exercise details logged.'}\n\n${state.notes?'Notes: '+state.notes+'\n\n':''}Progress: ${Math.max(0,88-state.weight).toFixed(1)} kg lost toward 75 kg.\n\nNext step: recover, refuel and keep building.`;$('saveStatus').textContent='✓ Achievement saved.'}
function renderHistory(){const h=$('history');h.innerHTML='';if(!state.history.length){h.innerHTML='<p class="muted">No sessions logged yet. Finish today and save your first achievement.</p>';return}state.history.forEach(x=>{const d=document.createElement('div');d.className='history-item';d.innerHTML=`<strong>${x.date} · ${x.weight.toFixed(1)} kg · ${x.rounds}/8 HYROX</strong><span>${x.done}/${x.total} activities completed${x.notes?' · '+x.notes:''}</span>`;h.appendChild(d)})}
$('saveBtn').addEventListener('click',save);$('emailBtn').addEventListener('click',()=>{const body=$('emailBody').value;if(!body){save();}const subject=encodeURIComponent(`HYROX 75 — ${plan[0]} achievement`);const text=encodeURIComponent($('emailBody').value);window.location.href=`mailto:?subject=${subject}&body=${text}`});
$('resetBtn').addEventListener('click',()=>{if(confirm('Reset local tracker data?')){localStorage.removeItem(KEY);location.reload()}});
roadmap.forEach((x,i)=>{const d=document.createElement('div');d.className='week'+(i===0?' current':'');d.innerHTML=`<b>Week ${i+1}</b><span>${x}</span>`;$('roadmap').appendChild(d)});renderStats();renderHistory();progress();
